export type EvidenceStatus = 'OBSERVED' | 'DERIVED' | 'UNAVAILABLE'
export type Confidence = 'HIGH' | 'MEDIUM' | 'UNAVAILABLE'

type Count = { value: string; count?: number; total?: number }
type LegacySlice = { slice: number; slotStart?: number; slotEnd?: number; uniquePrimarySigners?: number; newToSample?: number; returning?: number; successfulNewToSample?: number; successfulReturning?: number }
type LegacyEpisode = {
  generatedFrom?: string; generatedAt?: string; evidenceBoundary?: string
  sample?: { mint: string; startSlot?: number; endSlot?: number; transactions?: number; successes?: number; failures?: number; uniquePrimarySigners?: number; fetchFailures?: number; methodology?: string; selection?: string }
  participation?: LegacySlice[]
  concentration?: { overall?: { successfulTop1SharePercent?: number | null; successfulTop5SharePercent?: number | null; successfulTop10SharePercent?: number | null; hhi?: number | null }; bySlice?: Array<{ slice: number; successfulTransactions?: number; top1SuccessSharePercent?: number | null; top5SuccessSharePercent?: number | null; top10SuccessSharePercent?: number | null; successHhi?: number | null }> }
  failureEcology?: { bySlice?: Array<{ slice: number; failures?: number; explicitNoProfitOrRoute?: number; opaqueCustomErrors?: number; otherDocumentedFailures?: number }>; classes?: Count[]; noProfit?: { observedCount?: number; observedPrimarySignerAddresses?: number; observedProgramIds?: number; top1PrimarySignerSharePercent?: number | null; top3PrimarySignerSharePercent?: number | null; top5PrimarySignerSharePercent?: number | null; programs?: Count[] } }
}
type GenericEpisode = {
  methodologyVersion?: string; token?: { mint?: string; label?: string | null }; observationWindow?: { startSlot?: number; endSlot?: number }; evidenceBoundary?: string; sampling?: Record<string, unknown>
  metrics?: { transactions?: number; successes?: number; failures?: number; successRate?: number | null; uniquePrimarySigners?: number; successfulExecutionConcentration?: { top1?: number | null; top5?: number | null; top10?: number | null; hhi?: number | null }; failureClasses?: Count[]; failureConcentration?: { bySigner?: { top1?: number | null; top5?: number | null }; byProgram?: { top1?: number | null; top5?: number | null } } }
  slices?: Array<{ relativeSlice?: number; relativeStart?: number; relativeEnd?: number; slotStart?: number; slotEnd?: number; transactions?: number; successes?: number; failures?: number; successRate?: number | null; uniquePrimarySigners?: number; newToSampleSigners?: number; returningSigners?: number; successfulNewSigners?: number; successfulReturningSigners?: number }>
}

export type PulseObservation = { id: string; value: unknown; unit: string; evidenceBasis: string; evidenceStatus: EvidenceStatus; confidence: Confidence; safeInterpretation: string | null; prohibitedInterpretations: string[] }
export type ExecutionPulse = {
  schemaVersion: 'breadlines-execution-pulse-v0'; generatedAt: string; token: { mint: string; label: string | null }; observationWindow: { startSlot: number | null; endSlot: number | null; startUtc: null; endUtc: null }; methodology: { samplingSummary: string | null; selectionSummary: string | null; coverage: 'SAMPLED' | 'FULL_POPULATION' | 'UNKNOWN'; transactionCount: number | null; fetchFailures: number | null; evidenceBoundary: string | null }; coreMetrics: PulseObservation[]; chronologicalSlices: Array<Record<string, unknown>>; failureEcology: Record<string, unknown>; historicalBenchmark: { cohortDefinition: null; metric: null; percentile: null; comparison: null; sampleSize: null; methodologyVersion: null; status: 'UNAVAILABLE' }; limitations: string[]; provenance: { sourceArtifact: string; sourceGeneratedAt: string | null; sourceMethodologyVersion: string | null }; shareCardCandidates: Array<Record<string, unknown>>
}

const pct = (value: number | null | undefined) => value == null ? null : Number((value * 100).toFixed(1))
const count = (row: Count) => row.count ?? row.total ?? 0
const observation = (id: string, value: unknown, unit: string, evidenceBasis: string, safeInterpretation: string | null, prohibitedInterpretations: string[], available = value !== null): PulseObservation => ({ id, value: available ? value : null, unit, evidenceBasis, evidenceStatus: available ? 'DERIVED' : 'UNAVAILABLE', confidence: available ? 'HIGH' : 'UNAVAILABLE', safeInterpretation: available ? safeInterpretation : null, prohibitedInterpretations })

function normalize(input: LegacyEpisode | GenericEpisode) {
  if ('sample' in input && input.sample) {
    const x = input as LegacyEpisode, sample = x.sample!
    const successRate = sample.transactions ? sample.successes! / sample.transactions : null
    const bySlice = x.concentration?.bySlice ?? [], failures = x.failureEcology?.bySlice ?? []
    return {
      mint: sample.mint, label: null, startSlot: sample.startSlot ?? null, endSlot: sample.endSlot ?? null, transactions: sample.transactions ?? null, successes: sample.successes ?? null, failures: sample.failures ?? null, successRate, unique: sample.uniquePrimarySigners ?? null, top1: x.concentration?.overall?.successfulTop1SharePercent ?? null, top5: x.concentration?.overall?.successfulTop5SharePercent ?? null, top10: x.concentration?.overall?.successfulTop10SharePercent ?? null, hhi: null, classes: x.failureEcology?.classes ?? [], noProfit: x.failureEcology?.noProfit, slices: (x.participation ?? []).map((slice) => {
        const c = bySlice.find((entry) => entry.slice === slice.slice), f = failures.find((entry) => entry.slice === slice.slice)
        const successes = c?.successfulTransactions ?? null, failed = f?.failures ?? null
        return { index: slice.slice, relativeStart: null, relativeEnd: null, slotStart: slice.slotStart ?? null, slotEnd: slice.slotEnd ?? null, transactions: successes == null || failed == null ? null : successes + failed, successes, failures: failed, successRate: successes == null || failed == null || successes + failed === 0 ? null : successes / (successes + failed), uniquePrimarySigners: slice.uniquePrimarySigners ?? null, newSuccessfulParticipants: slice.successfulNewToSample ?? null, returningSuccessfulParticipants: slice.successfulReturning ?? null, newParticipants: slice.newToSample ?? null, returningParticipants: slice.returning ?? null }
      }), sampling: sample.methodology ?? null, selection: sample.selection ?? null, coverage: 'SAMPLED' as const, fetchFailures: sample.fetchFailures ?? null, boundary: x.evidenceBoundary ?? null, generatedAt: x.generatedAt ?? null, methodologyVersion: null,
    }
  }
  const x = input as GenericEpisode, metrics = x.metrics ?? {}
  return { mint: x.token?.mint ?? '', label: x.token?.label ?? null, startSlot: x.observationWindow?.startSlot ?? null, endSlot: x.observationWindow?.endSlot ?? null, transactions: metrics.transactions ?? null, successes: metrics.successes ?? null, failures: metrics.failures ?? null, successRate: metrics.successRate ?? null, unique: metrics.uniquePrimarySigners ?? null, top1: pct(metrics.successfulExecutionConcentration?.top1), top5: pct(metrics.successfulExecutionConcentration?.top5), top10: pct(metrics.successfulExecutionConcentration?.top10), hhi: metrics.successfulExecutionConcentration?.hhi ?? null, classes: metrics.failureClasses ?? [], noProfit: undefined, slices: (x.slices ?? []).map((s) => ({ index: s.relativeSlice ?? 0, relativeStart: s.relativeStart ?? null, relativeEnd: s.relativeEnd ?? null, slotStart: s.slotStart ?? null, slotEnd: s.slotEnd ?? null, transactions: s.transactions ?? null, successes: s.successes ?? null, failures: s.failures ?? null, successRate: s.successRate ?? null, uniquePrimarySigners: s.uniquePrimarySigners ?? null, newSuccessfulParticipants: s.successfulNewSigners ?? null, returningSuccessfulParticipants: s.successfulReturningSigners ?? null, newParticipants: s.newToSampleSigners ?? null, returningParticipants: s.returningSigners ?? null })), sampling: typeof x.sampling?.methodology === 'string' ? x.sampling.methodology : null, selection: typeof x.sampling?.selection === 'string' ? x.sampling.selection : null, coverage: 'SAMPLED' as const, fetchFailures: null, boundary: x.evidenceBoundary ?? null, generatedAt: null, methodologyVersion: x.methodologyVersion ?? null }
}

function candidate(headline: string, primaryValue: string, secondaryContext: string, evidenceStatement: string, whyInteresting: string, prohibitedClaims: string[]) { return { headline, primaryValue, secondaryContext, evidenceStatement, observationWindowQualifier: 'Observed sampled window; not a full-market claim.', methodologyQualifier: 'Receipt-derived, deterministic sampled evidence.', confidence: 'HIGH', whyInteresting, prohibitedClaims } }

export function transformMarketStructureEpisode(input: LegacyEpisode | GenericEpisode, options: { sourceArtifact: string; label?: string | null; generatedAt?: string } ): ExecutionPulse {
  const n = normalize(input)
  if (!n.mint) throw new Error('Episode must contain a token mint')
  const successPercent = pct(n.successRate)
  const metrics: PulseObservation[] = [
    observation('observed_executions', n.transactions, 'sampled transactions', 'Token-touching transactions retained under the source sampling contract.', n.transactions == null ? null : `${n.transactions.toLocaleString()} sampled token-touching transactions are represented.`, ['This covers every transaction in the market.', 'This measures token demand.']),
    observation('observed_primary_signers', n.unique, 'unique primary signer addresses', 'Deterministic primary-signer field in the source Episode.', n.unique == null ? null : `${n.unique.toLocaleString()} observed primary signer addresses appeared in the sample; successful-address-only coverage is unavailable in this source projection.`, ['These are unique people, users, buyers, or traders.']),
    observation('successful_execution_concentration', { top1SharePercent: n.top1, top5SharePercent: n.top5, top10SharePercent: n.top10, hhi: n.hhi }, 'share of sampled successful executions', 'Successful-execution concentration calculated by the source Episode.', n.top5 == null ? null : `The five most active observed signer addresses accounted for ${n.top5}% of sampled successful executions.`, ['Whales controlled the market.', 'Bots generated the activity.', 'These addresses controlled the token.'], [n.top1, n.top5, n.top10, n.hhi].some((value) => value != null)),
    observation('participation_through_time', n.slices.map((s) => ({ slice: s.index, newSuccessfulParticipants: s.newSuccessfulParticipants, returningSuccessfulParticipants: s.returningSuccessfulParticipants })), 'normalized chronological slices', 'First-observed and returning signer participation is calculated within the predetermined observation window.', n.slices.length ? 'Counts of new-to-sample and returning successful signer addresses are shown by chronological slice.' : null, ['New buyers kept arriving.', 'Adoption increased.', 'Participation broadened or narrowed.']),
    observation('failure_ecology', { failedExecutions: n.failures, classifiedFailureClasses: n.classes.map((x) => ({ value: x.value, count: count(x) })), explicitNoProfitOrRoute: n.noProfit ?? null }, 'observed failed executions', 'Failure classes and no-profit/no-route evidence from the source Episode.', n.failures == null ? null : `${n.failures.toLocaleString()} observed executions failed; the leading recorded failure class is ${n.classes[0] ? `${n.classes[0].value} (${count(n.classes[0]).toLocaleString()})` : 'unavailable'}.`, ['Failures were caused by the token team.', 'Every failure had the same cause.', 'Affected signer addresses are users.']),
    observation('execution_success_rate_through_time', { overallPercent: successPercent, slices: n.slices.map((s) => ({ slice: s.index, successRatePercent: pct(s.successRate) })) }, 'success rate', 'Successes divided by observed transactions in each normalized chronological slice.', successPercent == null ? null : `${successPercent}% of sampled executions succeeded; slice-level rates are shown without causal explanation.`, ['The token became more reliable because of a particular change.', 'Execution success predicts market performance.']),
  ]
  const cards = [
    n.top5 == null ? null : candidate('Successful execution concentration', `${n.top5}%`, 'of sampled successful executions came from the five most active observed signer addresses', `Top-5 successful-execution share was ${n.top5}%.`, 'A compact, directly observed concentration fact.', metrics[2].prohibitedInterpretations),
    successPercent == null ? null : candidate('Observed execution success rate', `${successPercent}%`, `${n.successes?.toLocaleString() ?? 'Unavailable'} of ${n.transactions?.toLocaleString() ?? 'unavailable'} sampled executions succeeded`, `Observed success rate was ${successPercent}% in the predetermined window.`, 'A simple reliability observation with a clear denominator.', metrics[5].prohibitedInterpretations),
    n.noProfit?.observedCount == null ? null : candidate('Explicit no-profit/no-route outcomes', `${n.noProfit.observedCount.toLocaleString()}`, `observed across ${n.noProfit.observedPrimarySignerAddresses?.toLocaleString() ?? 'unavailable'} primary signer addresses`, `${n.noProfit.observedCount} observed failures had explicit no-profit/no-route evidence.`, 'Specific receipt evidence, with concentration available in the full report.', metrics[4].prohibitedInterpretations),
  ].filter(Boolean) as Array<Record<string, unknown>>
  return { schemaVersion: 'breadlines-execution-pulse-v0', generatedAt: options.generatedAt ?? new Date().toISOString(), token: { mint: n.mint, label: options.label ?? n.label }, observationWindow: { startSlot: n.startSlot, endSlot: n.endSlot, startUtc: null, endUtc: null }, methodology: { samplingSummary: n.sampling, selectionSummary: n.selection, coverage: n.coverage, transactionCount: n.transactions, fetchFailures: n.fetchFailures, evidenceBoundary: n.boundary }, coreMetrics: metrics, chronologicalSlices: n.slices, failureEcology: { totalFailedExecutions: n.failures, classes: n.classes.map((x) => ({ value: x.value, count: count(x) })), explicitNoProfitOrRoute: n.noProfit ?? null }, historicalBenchmark: { cohortDefinition: null, metric: null, percentile: null, comparison: null, sampleSize: null, methodologyVersion: null, status: 'UNAVAILABLE' }, limitations: ['The source is a deterministic sample, not a complete market census.', 'Primary signer addresses are not proven people, users, buyers, traders, bots, or coordinated entities.', 'This report does not establish intent, causality, price impact, token quality, or any later market outcome.', 'Values unavailable in the source Episode remain unavailable here.'], provenance: { sourceArtifact: options.sourceArtifact, sourceGeneratedAt: n.generatedAt, sourceMethodologyVersion: n.methodologyVersion }, shareCardCandidates: cards }
}

export function renderPulseMarkdown(pulse: ExecutionPulse) {
  const metric = (id: string) => pulse.coreMetrics.find((x) => x.id === id)!
  const concentration = (metric('successful_execution_concentration').value ?? { top1SharePercent: null, top5SharePercent: null, top10SharePercent: null }) as { top1SharePercent: number | null; top5SharePercent: number | null; top10SharePercent: number | null }
  const reliability = metric('execution_success_rate_through_time').value as { overallPercent: number | null }
  const failures = pulse.failureEcology as { totalFailedExecutions: number | null; classes: Array<{ value: string; count: number }>; explicitNoProfitOrRoute: { observedCount?: number; observedPrimarySignerAddresses?: number; top5PrimarySignerSharePercent?: number | null } | null }
  const participation = pulse.chronologicalSlices as Array<{ index: number; newSuccessfulParticipants: number | null; returningSuccessfulParticipants: number | null }>
  const newInEverySlice = participation.length > 0 && participation.every((x) => (x.newSuccessfulParticipants ?? 0) > 0)
  const newTotal = participation.reduce((sum, x) => sum + (x.newSuccessfulParticipants ?? 0), 0)
  const returningTotal = participation.reduce((sum, x) => sum + (x.returningSuccessfulParticipants ?? 0), 0)
  return `# ${pulse.token.label ?? pulse.token.mint} — Breadlines Execution Pulse\n\n**Observation window:** slots ${pulse.observationWindow.startSlot ?? 'unavailable'}–${pulse.observationWindow.endSlot ?? 'unavailable'}  \n**Transactions represented:** ${pulse.methodology.transactionCount?.toLocaleString() ?? 'unavailable'} sampled token-touching transactions  \n**Methodology note:** ${pulse.methodology.samplingSummary ?? 'Sampling detail unavailable.'}\n\n## Participation\n\n${metric('observed_primary_signers').safeInterpretation ?? 'Primary-signer evidence is unavailable.'}\n\n## Successful Execution Concentration\n\n${metric('successful_execution_concentration').safeInterpretation ?? 'Successful-execution concentration is unavailable.'}${concentration.top1SharePercent == null ? '' : ` Top address share: ${concentration.top1SharePercent}%.`}${concentration.top10SharePercent == null ? '' : ` Top ten share: ${concentration.top10SharePercent}%.`}\n\n## Participation Through Time\n\n${newInEverySlice ? 'New-to-sample successful signer addresses appeared in every chronological slice.' : 'New-to-sample and returning successful signer-address counts are shown in the data artifact by chronological slice.'} The source recorded ${newTotal.toLocaleString()} slice-level new-successful-address observations and ${returningTotal.toLocaleString()} slice-level returning-successful-address observations; these are address observations, not counts of real-world entities.\n\n## Failure Ecology\n\n${metric('failure_ecology').safeInterpretation ?? 'Failure evidence is unavailable.'}${failures.explicitNoProfitOrRoute?.observedCount == null ? '' : ` ${failures.explicitNoProfitOrRoute.observedCount.toLocaleString()} had explicit no-profit/no-route evidence across ${failures.explicitNoProfitOrRoute.observedPrimarySignerAddresses?.toLocaleString() ?? 'unavailable'} observed primary signer addresses.`}\n\n## Execution Reliability\n\n${metric('execution_success_rate_through_time').safeInterpretation ?? 'Execution reliability evidence is unavailable.'}\n\n## What Breadlines Can Say\n\nThis report describes receipt-derived execution and address-participation patterns within the sampled observation window. It keeps transaction outcomes, signer recurrence, concentration, and documented failure evidence separate from speculation.\n\n## What Breadlines Cannot Say\n\nIt cannot identify real-world entities, establish intent or coordination, explain why a rate changed, measure the complete market, or make claims about price, token quality, or future performance.\n\n## Methodology and Provenance\n\nCoverage is **${pulse.methodology.coverage.toLowerCase()}**. Selection: ${pulse.methodology.selectionSummary ?? 'unavailable'}. Source: ${pulse.provenance.sourceArtifact}. Historical comparison is unavailable in v0.\n`
}
