import { readFile, rename, writeFile } from 'node:fs/promises'
import path from 'node:path'

type Json = Record<string, any>
function percentile(values: number[], p: number) { if (!values.length) return null; const sorted = [...values].sort((a, b) => a - b), i = (sorted.length - 1) * p, lo = Math.floor(i), hi = Math.ceil(i); return sorted[lo] + (sorted[hi] - sorted[lo]) * (i - lo) }
async function atomic(file: string, value: unknown) { const temp = `${file}.${process.pid}.tmp`; await writeFile(temp, `${JSON.stringify(value, null, 2)}\n`); await rename(temp, file) }
async function main() {
  const research = path.resolve('research/market-structure'), probe = JSON.parse(await readFile(path.join(research, 'transport-probe-5.json'), 'utf8')) as { selected: Array<{ mint: string }> }
  const operations: Json[] = []
  for (const row of probe.selected) { const operation = await readFile(path.join(research, 'full-cohort', row.mint, 'operations.json'), 'utf8').then(JSON.parse).catch(() => null); if (operation) operations.push(operation) }
  const transports = operations.map((operation) => operation.transport).filter(Boolean), latencies = transports.flatMap((transport: Json) => Object.values(transport.methods ?? {}).flatMap((method: any) => method.latencyMs ?? [])).filter((value): value is number => typeof value === 'number')
  const perSecond = transports.flatMap((transport: Json) => Object.entries(transport.requestsBySecond ?? {})).reduce((map, [time, count]) => { map.set(time, (map.get(time) ?? 0) + Number(count)); return map }, new Map<string, number>())
  const perMinute = transports.flatMap((transport: Json) => Object.entries(transport.requestsByMinute ?? {})).reduce((map, [time, count]) => { map.set(time, (map.get(time) ?? 0) + Number(count)); return map }, new Map<string, number>())
  const methods = transports.flatMap((transport: Json) => Object.entries(transport.methods ?? {})).reduce((map, [method, value]) => { const prior = map.get(method) ?? { attempts: 0, successes: 0, failures: 0, http429: 0 }; const stats = value as Json; map.set(method, { attempts: prior.attempts + (stats.attempts ?? 0), successes: prior.successes + (stats.successes ?? 0), failures: prior.failures + (stats.failures ?? 0), http429: prior.http429 + (stats.http429 ?? 0) }); return map }, new Map<string, Json>())
  const methodRows = [...methods.values()], totalRequests = methodRows.reduce((sum, method) => sum + method.attempts, 0), runtime = operations.reduce((sum, operation) => sum + (operation.runtimeSecondsThisRun ?? 0), 0), retryRequests = transports.flatMap((transport: Json) => transport.retryCountsByRequest ?? [])
  const report = { generatedAt: new Date().toISOString(), selectedMints: probe.selected.map((row) => row.mint), complete: operations.filter((operation) => operation.complete).length, incomplete: operations.filter((operation) => !operation.complete).map((operation) => ({ mint: operation.mint, reason: operation.incompleteReason, retryable: operation.retryable === true })), totalRequests, totalRuntimeSeconds: runtime, effectiveRps: runtime ? totalRequests / runtime : null, requestsPerSecond: Object.fromEntries(perSecond), requestsPerMinute: Object.fromEntries(perMinute), peakConcurrentInFlight: Math.max(0, ...transports.map((transport: Json) => transport.peakInFlight ?? 0)), methods: Object.fromEntries(methods), http429Count: methodRows.reduce((sum, method) => sum + method.http429, 0), transportErrorCount: methodRows.reduce((sum, method) => sum + method.failures - method.http429, 0), responseLatencyMs: { p50: percentile(latencies, .5), p95: percentile(latencies, .95), samples: latencies.length }, retryCountsByRequest: retryRequests, retryStormCheck: { concurrentInFlightExceededOne: Math.max(0, ...transports.map((transport: Json) => transport.peakInFlight ?? 0)) > 1, requestsWithRetries: retryRequests.filter((request: Json) => request.retries > 0).length, maxRetriesForOneRequest: Math.max(0, ...retryRequests.map((request: Json) => request.retries ?? 0)), note: 'Probe-only scheduler telemetry. One scheduler permit is acquired per individual JSON-RPC method call; a retry sleeps through backoff before acquiring a new permit.' } }
  await atomic(path.join(research, 'transport-probe-5-report.json'), report)
  await writeFile(path.join(research, 'transport-probe-5-report.md'), `# Transport probe report\n\n- Complete: ${report.complete} / 5\n- HTTP 429: ${report.http429Count}\n- Transport errors: ${report.transportErrorCount}\n- Total requests: ${report.totalRequests}\n- Effective RPS: ${report.effectiveRps}\n- Runtime seconds: ${report.totalRuntimeSeconds}\n- Response latency p50/p95 ms: ${report.responseLatencyMs.p50} / ${report.responseLatencyMs.p95}\n- Peak concurrent in-flight requests: ${report.peakConcurrentInFlight}\n- Retry storm detected: ${report.retryStormCheck.concurrentInFlightExceededOne}\n\nSee the JSON report for per-second/minute request counts, per-method 429s, and retry count per request.\n`)
  console.log(`Transport probe report: ${report.complete}/5 complete; ${report.http429Count} 429s; ${report.totalRequests} requests`)
}
void main()
