import { readFile, rename, writeFile } from 'node:fs/promises'
import path from 'node:path'

const OUT = path.resolve('research/slot-time-300ms-boundary')
const INPUT = path.join(OUT, 'analysis.json')
const STABILITY = path.join(OUT, 'stability-analysis.json')
const OUTPUT = path.join(OUT, 'full-window-report.md')

const number = (value: unknown) => typeof value === 'number' ? value.toLocaleString('en-US', { maximumFractionDigits: 2 }) : 'UNKNOWN'
const percent = (value: unknown) => typeof value === 'number' ? `${(value * 100).toFixed(2)}%` : 'UNKNOWN'
const delta = (before: unknown, after: unknown) => typeof before === 'number' && typeof after === 'number' && before !== 0 ? `${((after - before) / before * 100).toFixed(2)}%` : 'UNKNOWN'
const pp = (before: unknown, after: unknown) => typeof before === 'number' && typeof after === 'number' ? `${((after - before) * 100).toFixed(2)} pp` : 'UNKNOWN'
async function atomic(file: string, value: string) { const temp = `${file}.${process.pid}.tmp`; await writeFile(temp, value); for (let attempt = 0; attempt < 4; attempt++) try { await rename(temp, file); return } catch (error) { if (attempt === 3) throw error; await new Promise(resolve => setTimeout(resolve, 100 * (attempt + 1))) } }
function row(label: string, before: unknown, after: unknown, format: (value: unknown) => string = number, change: (before: unknown, after: unknown) => string = delta) { return `| ${label} | ${format(before)} | ${format(after)} | ${change(before, after)} |` }
function pairTable(title: string, pair: any) {
  const b = pair.before, a = pair.after
  return `## ${title}\n\n| Sampled-ledger metric | Before | After | Change |\n| --- | ---: | ---: | ---: |\n${row('Sampled blocks', b.sampledBlocks, a.sampledBlocks)}\n${row('Sampled landed non-vote transactions', b.sampledLandedNonVoteTransactions, a.sampledLandedNonVoteTransactions)}\n${row('Landed successes', b.success.count, a.success.count)}\n${row('Success rate', b.success.rate, a.success.rate, percent, pp)}\n${row('Landed failures', b.failure.count, a.failure.count)}\n${row('Failure rate', b.failure.rate, a.failure.rate, percent, pp)}\n${row('Total CU consumed', b.computeUnits.total, a.computeUnits.total)}\n${row('Successful CU consumed', b.computeUnits.success, a.computeUnits.success)}\n${row('Failed CU consumed', b.computeUnits.failed, a.computeUnits.failed)}\n${row('Failed-CU share', b.computeUnits.failedCuShare, a.computeUnits.failedCuShare, percent, pp)}\n${row('CU/tx median', b.computeUnits.distribution.median, a.computeUnits.distribution.median)}\n${row('CU/tx P90', b.computeUnits.distribution.p90, a.computeUnits.distribution.p90)}\n${row('CU/tx P95', b.computeUnits.distribution.p95, a.computeUnits.distribution.p95)}\n${row('Cost units/tx median', b.costUnits.distribution.median, a.costUnits.distribution.median)}\n${row('Cost units/tx P90', b.costUnits.distribution.p90, a.costUnits.distribution.p90)}\n${row('Cost units/tx P95', b.costUnits.distribution.p95, a.costUnits.distribution.p95)}\n${row('Cost-unit availability', b.costUnits.availabilityRate, a.costUnits.availabilityRate, percent, pp)}\n${row('Total fees (lamports)', b.feesLamports.total, a.feesLamports.total)}\n${row('Success fees (lamports)', b.feesLamports.success, a.feesLamports.success)}\n${row('Failure fees (lamports)', b.feesLamports.failed, a.feesLamports.failed)}\n${row('Reconstructed priority-fee median (lamports)', b.priorityFeeLamports.distribution.median, a.priorityFeeLamports.distribution.median)}\n${row('Reconstructed priority-fee P90 (lamports)', b.priorityFeeLamports.distribution.p90, a.priorityFeeLamports.distribution.p90)}\n${row('Reconstructed priority-fee P95 (lamports)', b.priorityFeeLamports.distribution.p95, a.priorityFeeLamports.distribution.p95)}\n${row('Priority-fee reconstruction coverage', b.priorityFeeLamports.reconstructableRate, a.priorityFeeLamports.reconstructableRate, percent, pp)}\n${row('Median non-vote tx/block', b.perBlock.transactions.median, a.perBlock.transactions.median)}\n${row('Median non-vote CU/block', b.perBlock.nonVoteCu.median, a.perBlock.nonVoteCu.median)}\n${row('Median all-landed CU utilization', b.perBlock.allLandedCuUtilization.median, a.perBlock.allLandedCuUtilization.median, percent, pp)}\n${row('Applicable block CU limit', b.perBlock.applicableBlockCuLimit, a.perBlock.applicableBlockCuLimit)}\n\n`
}
function bucketTable(title: string, buckets: any[]) {
  return `### ${title}\n\n| Bucket | Sampled blocks | Non-vote tx | Success rate | Failure rate | Failed-CU share | Median CU/tx | Median cost units/tx | Median priority fee | Median tx/block | Median CU/block | All-landed CU utilization |\n| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n${buckets.map(bucket => `| ${bucket.index} | ${number(bucket.sampledBlocks)} | ${number(bucket.sampledLandedNonVoteTransactions)} | ${percent(bucket.success.rate)} | ${percent(bucket.failure.rate)} | ${percent(bucket.computeUnits.failedCuShare)} | ${number(bucket.computeUnits.distribution.median)} | ${number(bucket.costUnits.distribution.median)} | ${number(bucket.priorityFeeLamports.distribution.median)} | ${number(bucket.perBlock.transactions.median)} | ${number(bucket.perBlock.nonVoteCu.median)} | ${percent(bucket.perBlock.allLandedCuUtilization.median)} |`).join('\n')}\n\n`
}
function bucketSection(title: string, pair: any) { return `## ${title} chronological buckets\n\n${bucketTable('Before', pair.beforeBuckets)}${bucketTable('After', pair.afterBuckets)}` }
async function main() {
  const report = JSON.parse(await readFile(INPUT, 'utf8')), stability = JSON.parse(await readFile(STABILITY, 'utf8'))
  const text = `# Solana 350ms → 300ms: full sampled-ledger window report\n\n## Boundary and sample contract\n\n- Boundary: epoch 1024, slot 442,368,000, \`${new Date(report.boundary.boundaryBlockTime * 1_000).toISOString()}\`.
- Both adjacent boundary slots resolve to the same estimated block-time second; the ledger does not resolve a finer instant from that pair.
- Population: landed transactions in deterministically selected full blocks. Vote-only transactions are excluded only when every outer instruction is Vote or Compute Budget and at least one is Vote.
- The unbuffered comparisons are wall-clock windows meeting at the epoch boundary. Independent deterministic sampling leaves an observed coverage gap between the closest selected blocks; it is not treated as a zero-width buffer.
- Buffered 6h comparison: fixed 10-minute exclusion on each side of the boundary before selection.
- 12h: deferred, not collected.
- Capacity denominator: 87.5M cost units before and 75M after. The sampled per-block maxima independently approached these ceilings without exceeding them; this supports those denominators but is not a causal before/after result.
- Every count is a sampled-ledger quantity, not a network total.\n\n${pairTable('Unbuffered 1-hour window', report.primary60Minutes)}${pairTable('Unbuffered 3-hour window', report.robustness3Hours)}${pairTable('Unbuffered 6-hour window', report.extended6Hours)}${pairTable('Buffered 6-hour window', report.bufferedVariants.extended6Hours)}${bucketSection('Unbuffered 1-hour', report.primary60Minutes)}${bucketSection('Unbuffered 3-hour', report.robustness3Hours)}${bucketSection('Unbuffered 6-hour', report.extended6Hours)}${bucketSection('Buffered 6-hour', report.bufferedVariants.extended6Hours)}## Locked stability read\n\nNo metric qualified as stable under the preregistered direction, fee-trimming, and within-window bucket-variation gates. See [stability-analysis.md](stability-analysis.md) and [stability-preregistration.md](stability-preregistration.md).\n\n## What is unmeasurable from landed-ledger data\n\n- Sender geography, sender network path, ingress point, validator targeting, or any EU/US/AP comparison. These require sender/network telemetry rather than a block receipt.
- Transactions that were submitted but never landed, including dropped, expired, rejected, or otherwise unseen traffic.
- End-to-end submission latency, leader receipt time, mempool residence, forwarding behaviour, or client-side retry timing.
- Causal impact of the 350ms → 300ms transition. The study records a time-adjacent change in sampled landed execution; transaction mix, leaders, fee-market conditions, time-of-day, concurrent releases, and sampling variation remain alternatives.
- Address identity, human/bot/user classification, application ownership, or sender intent.
- Whether a failure was economically avoidable, whether a trade would have filled, quote quality, price impact, profitability, or post-window market outcome.
- A complete application-class or protocol breakdown unless a program-level attribution rule is separately defined and audited.
- A native priority fee when the relevant Compute Budget instruction data is absent or cannot be deterministically decoded. Reconstruction coverage is reported instead.
- Full-network throughput, full-population success/failure rates, or an exact global utilization census; this report samples deterministically selected landed blocks.\n\n## What the ledger does establish\n\nFor the sampled landed population it establishes receipt success/failure, fees, consumed compute units, cost units when present, selected Compute Budget settings when reconstructable, and per-block composition. It can therefore describe execution already included in blocks, but not why it was submitted, how it travelled to a leader, or what traffic failed to appear on-chain.\n\n## Provenance\n\n- Raw sampled aggregates: [analysis.json](analysis.json)
- Deterministic block plan: [sampling-plan.json](sampling-plan.json)
- Append-only index: [block-index.jsonl](block-index.jsonl)
- Fee trimming sensitivity: [fee-enrichment.json](fee-enrichment.json)
- Stability rules and output: [stability-preregistration.md](stability-preregistration.md), [stability-analysis.md](stability-analysis.md)\n`
  await atomic(OUTPUT, text)
}
void main()
