import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

type Instruction = { programIdIndex?: number }
type Tx = { transaction?: { message?: { accountKeys?: string[]; instructions?: Instruction[] } }; meta?: { err?: unknown; computeUnitsConsumed?: number } }
type Block = { blockTime?: number | null; transactions?: Tx[] }
type Saved = { slot:number; blockTime:number|null; window:string; aggregate:{ landedNonVote:number; success:number; failure:number; transactionParseUnknown:number } }
const OUT = path.resolve('research/slot-time-300ms-boundary')
const VOTE='Vote111111111111111111111111111111111111111', COMPUTE='ComputeBudget111111111111111111111111111111111111'
const BOUNDARY_SLOT=442_368_000, BOUNDARY_TIME=1_787_930_703, RPS=1
let next=0
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms))
const iso=(time:number)=>new Date(time*1_000).toISOString()
async function apiKey(){ const env=await readFile('.env.local','utf8'); const key=env.match(/^HELIUS_API_KEY=(.+)$/m)?.[1]?.trim(); if(!key)throw new Error('HELIUS_API_KEY is required'); return key }
async function rpc<T>(key:string,method:string,params:unknown[]):Promise<T>{ for(let attempt=0;attempt<6;attempt++){const wait=Math.max(0,next-Date.now());if(wait)await sleep(wait);next=Math.max(next,Date.now())+1_000/RPS;try{const res=await fetch(`https://mainnet.helius-rpc.com/?api-key=${key}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:AbortSignal.timeout(60_000)});const body=await res.json() as {result?:T,error?:{message?:string}};if(res.ok&&!body.error&&body.result!==undefined)return body.result;if(!(res.status===429||res.status>=500)||attempt===5)throw new Error(body.error?.message??`HTTP ${res.status}`)}catch(error){if(attempt===5)throw error}await sleep(Math.min(30_000,1_000*2**attempt+Math.floor(Math.random()*250)))}throw new Error('unreachable') }
async function firstSlotAtOrAfter(key:string,target:number,low:number,high:number){while(low<high){const mid=Math.floor((low+high)/2),time=await rpc<number|null>(key,'getBlockTime',[mid]);if(time==null||time<target)low=mid+1;else high=mid}return low}
function voteOnly(tx:Tx){const keys=tx.transaction?.message?.accountKeys,instructions=tx.transaction?.message?.instructions;if(!keys||!instructions)return null;const programs=instructions.map(ix=>keys[ix.programIdIndex??-1]);return programs.includes(VOTE)&&programs.every(p=>p===VOTE||p===COMPUTE)}
function aggregate(block:Block){let landedNonVote=0,success=0,failure=0,transactionParseUnknown=0;for(const tx of block.transactions??[]){const only=voteOnly(tx);if(only==null){transactionParseUnknown++;continue}if(only)continue;landedNonVote++;if(tx.meta?.err==null)success++;else failure++}return {landedNonVote,success,failure,transactionParseUnknown}}
function pick<T>(items:T[],count:number){return Array.from({length:Math.min(count,items.length)},(_,i)=>items[Math.floor((i+.5)*items.length/Math.min(count,items.length))])}
function errorCategory(err:unknown){if(!err||typeof err!=='object')return 'UNKNOWN_ERROR_SHAPE';const key=Object.keys(err as Record<string,unknown>)[0];return key??'UNKNOWN_ERROR_SHAPE'}
function context(tx:Tx){const err=tx.meta?.err as {InstructionError?:[number,unknown]}|undefined;const ix=err?.InstructionError?.[0];if(!Number.isInteger(ix))return 'NON_INSTRUCTION_ERROR';return tx.transaction?.message?.accountKeys?.[tx.transaction?.message?.instructions?.[ix!]?.programIdIndex??-1]??'UNRESOLVED_OUTER_PROGRAM'}
async function main(){
 const key=await apiKey();const [schedule,boundary,before]=await Promise.all([rpc<{firstNormalEpoch:number;firstNormalSlot:number;slotsPerEpoch:number;warmup:boolean}>(key,'getEpochSchedule',[]),rpc<number|null>(key,'getBlockTime',[BOUNDARY_SLOT]),rpc<number|null>(key,'getBlockTime',[BOUNDARY_SLOT-1])]);
 const checkpoint=JSON.parse(await readFile(path.join(OUT,'checkpoint.json'),'utf8')) as {samples:Saved[],methodology:unknown,boundary:unknown};const selected=['before_60m','after_60m'].flatMap(window=>pick(checkpoint.samples.filter(x=>x.window===window).sort((a,b)=>a.slot-b.slot),10));
 const selectionRanges=Object.fromEntries((await Promise.all([1,3].map(async hours=>{const startBefore=await firstSlotAtOrAfter(key,BOUNDARY_TIME-hours*3600,Math.max(0,BOUNDARY_SLOT-Math.ceil(hours*3600/.25)),BOUNDARY_SLOT-1);const afterExclusive=await firstSlotAtOrAfter(key,BOUNDARY_TIME+hours*3600,BOUNDARY_SLOT,BOUNDARY_SLOT+Math.ceil(hours*3600/.2));const endAfter=afterExclusive-1;const [beforeStartTime,beforeEndTime,afterStartTime,afterEndTime]=await Promise.all([rpc<number|null>(key,'getBlockTime',[startBefore]),rpc<number|null>(key,'getBlockTime',[BOUNDARY_SLOT-1]),rpc<number|null>(key,'getBlockTime',[BOUNDARY_SLOT]),rpc<number|null>(key,'getBlockTime',[endAfter])]);return [[`before_${hours}h`,{startSlot:startBefore,endSlot:BOUNDARY_SLOT-1,startBlockTime:beforeStartTime,endBlockTime:beforeEndTime}],[`after_${hours}h`,{startSlot:BOUNDARY_SLOT,endSlot:endAfter,startBlockTime:afterStartTime,endBlockTime:afterEndTime}]]}))).flat())
 const failures:{category:string;context:string}[]=[];const verification:{slot:number;window:string;blockTime:number|null;saved:ReturnType<typeof aggregate>;recomputed:ReturnType<typeof aggregate>;matches:boolean}[]=[];
 for(const sample of selected){const block=await rpc<Block|null>(key,'getBlock',[sample.slot,{encoding:'json',transactionDetails:'full',rewards:false,maxSupportedTransactionVersion:1}]);if(!block)throw new Error(`Missing sampled block ${sample.slot}`);const recomputed=aggregate(block);const saved={landedNonVote:sample.aggregate.landedNonVote,success:sample.aggregate.success,failure:sample.aggregate.failure,transactionParseUnknown:sample.aggregate.transactionParseUnknown};verification.push({slot:sample.slot,window:sample.window,blockTime:block.blockTime??null,saved,recomputed,matches:['landedNonVote','success','failure','transactionParseUnknown'].every(k=>saved[k as keyof typeof saved]===recomputed[k as keyof ReturnType<typeof aggregate>])});for(const tx of block.transactions??[])if(voteOnly(tx)===false&&tx.meta?.err!=null)failures.push({category:errorCategory(tx.meta.err),context:context(tx)})}
 const tally=(values:string[])=>Object.entries(values.reduce((out,value)=>(out[value]=(out[value]??0)+1,out),{} as Record<string,number>)).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([label,count])=>({label,count,share:failures.length?count/failures.length:null}));
 const samplesByWindow=Object.fromEntries(['before_60m','after_60m','before_3h','after_3h'].map(window=>{const rows=checkpoint.samples.filter(x=>x.window===window);return [window,{count:rows.length,minSlot:Math.min(...rows.map(x=>x.slot)),maxSlot:Math.max(...rows.map(x=>x.slot)),minBlockTime:Math.min(...rows.map(x=>x.blockTime??Infinity)),maxBlockTime:Math.max(...rows.map(x=>x.blockTime??-Infinity))}]}))
 const output={
  generatedAt:new Date().toISOString(),
  authoritativeRpc:{getEpochSchedule:schedule,getBlockTime:{slot442367999:before,slot442368000:boundary},epochCalculation:{slot442367999:Math.floor((442367999-schedule.firstNormalSlot)/schedule.slotsPerEpoch)+schedule.firstNormalEpoch,slot442368000:Math.floor((BOUNDARY_SLOT-schedule.firstNormalSlot)/schedule.slotsPerEpoch)+schedule.firstNormalEpoch},authoritativeBoundary:{slot:BOUNDARY_SLOT,unix:BOUNDARY_TIME,utc:iso(BOUNDARY_TIME),rpcMatchesStored:boundary===BOUNDARY_TIME&&before===BOUNDARY_TIME}},
  declaredWindows:{before60:{startUtc:iso(BOUNDARY_TIME-3600),endUtc:iso(BOUNDARY_TIME),endExclusive:true},after60:{startUtc:iso(BOUNDARY_TIME),endUtc:iso(BOUNDARY_TIME+3600),endExclusive:true},before3h:{startUtc:iso(BOUNDARY_TIME-10800),endUtc:iso(BOUNDARY_TIME),endExclusive:true},after3h:{startUtc:iso(BOUNDARY_TIME),endUtc:iso(BOUNDARY_TIME+10800),endExclusive:true}},
  checkpointEvidence:{rawBoundary:checkpoint.boundary,rawMethodology:checkpoint.methodology,samplesByWindow,selectionRanges},
  voteFailureSanity:{voteOnlyDefinition:'Outer instruction programs include Vote and every outer program is Vote or Compute Budget; all other parseable landed transactions are retained.',failureDefinition:'Retained transaction has meta.err != null.',savedTransactionParseUnknown:checkpoint.samples.reduce((sum,sample)=>sum+sample.aggregate.transactionParseUnknown,0),sampledBlocksRechecked:selected.length,allRecomputedAggregatesMatchCheckpoint:verification.every(x=>x.matches),verification,auditSample:{landedNonVote:verification.reduce((sum,row)=>sum+row.recomputed.landedNonVote,0),success:verification.reduce((sum,row)=>sum+row.recomputed.success,0),failure:verification.reduce((sum,row)=>sum+row.recomputed.failure,0),failureRate:failures.length/verification.reduce((sum,row)=>sum+row.recomputed.landedNonVote,0)},failedRetainedTransactionsInAuditSample:failures.length,topMetaErrorCategories:tally(failures.map(x=>x.category)),topFailingOuterInstructionContexts:tally(failures.map(x=>x.context)),contaminationFlags:verification.some(x=>x.recomputed.transactionParseUnknown>0)?['Some sampled blocks contain transaction records without enough outer-message data to classify; these are tracked and excluded.']:[]},
  bufferPreRegistration:{status:'DECLARED_NOT_COLLECTED',bufferSeconds:600,buffer:'10 minutes fixed before inspecting buffered results',unbuffered:'Existing windows remain [boundary-duration, boundary) and [boundary, boundary+duration).',buffered:'For each duration d, use [boundary-d, boundary-10m) and [boundary+10m, boundary+d); the 20-minute central interval is excluded and both sides remain equal-duration.'},
  staleTimestampAudit:{searchedTimestamp:'2026-08-28T19:25:03.000Z',foundInPersistedStudyArtifacts:false,conclusion:'No checkpoint, code, analysis JSON, Markdown report, or sampled block range uses the stale 19:25:03Z timestamp. It was a status-message presentation error, not a collection or calculation input.'}
 }
 await writeFile(path.join(OUT,'methodology-integrity-audit.json'),`${JSON.stringify(output,null,2)}\n`);console.log(JSON.stringify({ok:true,checked:selected.length,failures:failures.length},null,2))
}
void main()
