import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import path from 'node:path'

const OUT = path.resolve('research/slot-time-300ms-boundary')
const ANALYSIS = path.join(OUT, 'analysis.json')
const OUTPUT = path.join(OUT, 'prior-day-same-hour-control.json')
const MARKDOWN = path.join(OUT, 'prior-day-same-hour-control.md')
const VOTE = 'Vote111111111111111111111111111111111111111'
const COMPUTE = 'ComputeBudget111111111111111111111111111111'
const RPS = 4
const MAX_IN_FLIGHT = 4
const SAMPLE_COUNT = 120

type Tx = { transaction?: { message?: { accountKeys?: string[]; instructions?: Array<{ programIdIndex?: number }> } }; meta?: { err?: unknown } }
type Block = { blockTime?: number | null; transactions?: Tx[] }
const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))
async function atomic(file: string, value: unknown) { const temp = `${file}.${process.pid}.tmp`; await writeFile(temp, `${JSON.stringify(value, null, 2)}\n`); for (let attempt = 0; attempt < 4; attempt++) try { await rename(temp, file); return } catch (error) { if (attempt === 3) throw error; await sleep(100 * (attempt + 1)) } }
async function apiKey() { const text = await readFile('.env.local', 'utf8'), key = text.match(/^HELIUS_API_KEY=(.+)$/m)?.[1]?.trim(); if (!key) throw new Error('HELIUS_API_KEY is required'); return key }
let nextRequestAt = 0
async function rpc<T>(key: string, method: string, params: unknown[]): Promise<T> { for (let attempt = 0; attempt < 8; attempt++) { const wait = Math.max(0, nextRequestAt - Date.now()); if (wait) await sleep(wait); nextRequestAt = Math.max(nextRequestAt, Date.now()) + 1_000 / RPS; let retryAfter = 0; try { const response = await fetch(`https://mainnet.helius-rpc.com/?api-key=${key}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }), signal: AbortSignal.timeout(60_000) }); const body = await response.json() as { result?: T; error?: { message?: string } }; if (response.ok && !body.error && body.result !== undefined) return body.result; if (response.status !== 429 && response.status < 500) throw new Error(body.error?.message ?? `HTTP ${response.status}`); const seconds = Number(response.headers.get('retry-after')); retryAfter = Number.isFinite(seconds) ? seconds * 1_000 : 0 } catch (error) { if (attempt === 7) throw error } const backoff = Math.max(retryAfter, Math.min(60_000, 1_000 * 2 ** attempt + Math.floor(Math.random() * 500))); nextRequestAt = Math.max(nextRequestAt, Date.now() + backoff); await sleep(backoff) } throw new Error(`${method} exhausted retries`) }
async function pool<T, R>(items: T[], work: (item: T) => Promise<R>) { const results: R[] = [], queue = [...items]; const workers = Array.from({ length: Math.min(MAX_IN_FLIGHT, items.length) }, async () => { while (queue.length) results.push(await work(queue.shift()!)) }); await Promise.all(workers); return results }
async function firstSlotAtOrAfter(key: string, target: number, low: number, high: number) { while (low < high) { const mid = Math.floor((low + high) / 2), time = await rpc<number | null>(key, 'getBlockTime', [mid]); if (time == null || time < target) low = mid + 1; else high = mid } return low }
function pick(slots: number[]) { if (slots.length < SAMPLE_COUNT) throw new Error(`Only ${slots.length} landed blocks for fixed sample ${SAMPLE_COUNT}`); return Array.from({ length: SAMPLE_COUNT }, (_, index) => slots[Math.floor((index + .5) * slots.length / SAMPLE_COUNT)]) }
function programs(tx: Tx) { const keys = tx.transaction?.message?.accountKeys, instructions = tx.transaction?.message?.instructions; return keys && instructions ? instructions.map(ix => keys[ix.programIdIndex ?? -1]) : null }
function voteOnly(programs: string[] | null) { return programs != null && programs.includes(VOTE) && programs.every(program => program === VOTE || program === COMPUTE) }
async function main() {
  await mkdir(OUT, { recursive: true })
  const analysis = JSON.parse(await readFile(ANALYSIS, 'utf8')), boundaryTime = analysis.boundary.boundaryBlockTime as number, boundarySlot = analysis.boundary.effectiveSlot as number
  const start = boundaryTime - 30 * 3600, end = boundaryTime - 24 * 3600, key = await apiKey()
  const startSlot = await firstSlotAtOrAfter(key, start, boundarySlot - 400_000, boundarySlot - 150_000)
  const endSlot = (await firstSlotAtOrAfter(key, end, startSlot, boundarySlot - 100_000)) - 1
  const cursors: number[] = []; for (let slot = startSlot; slot <= endSlot; slot += 500) cursors.push(slot)
  const pages = await pool(cursors, cursor => rpc<number[]>(key, 'getBlocks', [cursor, Math.min(endSlot, cursor + 499)]))
  const selected = pick(pages.flat().sort((a, b) => a - b))
  const rows = await pool(selected, async slot => { const block = await rpc<Block | null>(key, 'getBlock', [slot, { encoding: 'json', transactionDetails: 'full', rewards: false, maxSupportedTransactionVersion: 1 }]); if (!block?.blockTime) throw new Error(`Sampled block ${slot} unavailable or missing block time`); let landedNonVoteTransactions = 0, success = 0, failure = 0; for (const tx of block.transactions ?? []) { if (voteOnly(programs(tx))) continue; landedNonVoteTransactions++; if (tx.meta?.err == null) success++; else failure++ } const bucket = Math.floor((block.blockTime - start) / 3600) + 1; if (bucket < 1 || bucket > 6) throw new Error(`Slot ${slot} falls outside prior-day control window`); return { slot, blockTimeUtc: new Date(block.blockTime * 1_000).toISOString(), bucket, landedNonVoteTransactions, success, failure } })
  const controlBuckets = Array.from({ length: 6 }, (_, index) => { const bucket = index + 1, members = rows.filter(row => row.bucket === bucket), landedNonVoteTransactions = members.reduce((sum, row) => sum + row.landedNonVoteTransactions, 0), success = members.reduce((sum, row) => sum + row.success, 0), failure = members.reduce((sum, row) => sum + row.failure, 0); return { bucket, startUtc: new Date((start + index * 3600) * 1_000).toISOString(), endUtc: new Date((start + (index + 1) * 3600) * 1_000).toISOString(), sampledBlocks: members.length, sampledLandedNonVoteTransactions: landedNonVoteTransactions, success, failure, successRate: landedNonVoteTransactions ? success / landedNonVoteTransactions : null } })
  const transitionBuckets = analysis.extended6Hours.beforeBuckets.map((item: any) => ({ bucket: item.index, sampledBlocks: item.sampledBlocks, sampledLandedNonVoteTransactions: item.sampledLandedNonVoteTransactions, success: item.success.count, failure: item.failure.count, successRate: item.success.rate }))
  const output = { schemaVersion: 1, generatedAt: new Date().toISOString(), scope: 'Matched same-hour prior-day control. The prior-day window is 24 hours before the fixed six-hour pre-boundary window; it uses the same 120 evenly ranked landed-block count, six chronological buckets, and vote-only exclusion. This is a descriptive time-of-day check, not causal identification.', priorDayWindow: { startUtc: new Date(start * 1_000).toISOString(), endUtc: new Date(end * 1_000).toISOString(), startSlot, endSlot, landedCandidateBlocks: pages.flat().length, selectedSlots: selected }, transitionPreWindow: { startUtc: analysis.extended6Hours.before.window.startUtc, endUtc: analysis.extended6Hours.before.window.endUtc, selectedSlots: analysis.source.deterministicSamplingPlan }, bucketComparison: transitionBuckets.map((transition: any) => ({ bucket: transition.bucket, transitionPreBoundary: transition, priorDaySameHour: controlBuckets[transition.bucket - 1] })), rawPriorDayBlocks: rows.sort((a, b) => a.slot - b.slot) }
  await atomic(OUTPUT, output)
  await writeFile(MARKDOWN, `# Matched same-hour prior-day control\n\nThe control window is \`${new Date(start * 1_000).toISOString()}\` to \`${new Date(end * 1_000).toISOString()}\`, exactly 24 hours before the fixed pre-boundary window. It uses 120 deterministic evenly ranked landed blocks and the same vote-only exclusion.\n\n| Bucket | Transition-pre non-vote tx | Prior-day non-vote tx | Transition-pre success rate | Prior-day success rate |\n| --- | ---: | ---: | ---: | ---: |\n${output.bucketComparison.map((item: any) => `| ${item.bucket} | ${item.transitionPreBoundary.sampledLandedNonVoteTransactions.toLocaleString()} | ${item.priorDaySameHour.sampledLandedNonVoteTransactions.toLocaleString()} | ${(item.transitionPreBoundary.successRate * 100).toFixed(2)}% | ${(item.priorDaySameHour.successRate * 100).toFixed(2)}% |`).join('\n')}\n\nInterpretation boundary: similar or different bucket shapes can motivate or weaken a time-of-day hypothesis, but this one matched-day control cannot identify its cause.\n`)
}
void main()
