import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { collectComputeBudget, deriveExecutionState, derivePriorityFeeLamports, findExplicitProgramError, type ReceiptRpcInstruction, type ReceiptRpcTransaction } from '../lib/receipt-evidence.ts'

const TOAD_MINT = 'A13oRB9FFaiUjfi6LdCg6p9ka1u8SfGkUFs4SKvPpump'
const SLICE_COUNT = 20
type Entry = { signature: string; metadata: Record<string, unknown> }
type Key = string | { pubkey?: string; signer?: boolean; writable?: boolean }
type Balance = { accountIndex?: number; mint?: string; owner?: string; uiTokenAmount?: { amount?: string; decimals?: number } }
type RpcTx = ReceiptRpcTransaction & { slot?: number; blockTime?: number | null; meta?: ReceiptRpcTransaction['meta'] & { innerInstructions?: Array<{ instructions?: ReceiptRpcInstruction[] }>; preTokenBalances?: Balance[]; postTokenBalances?: Balance[] }; transaction?: ReceiptRpcTransaction['transaction'] & { message?: { accountKeys?: Key[]; instructions?: ReceiptRpcInstruction[] } } }
type Cache = Record<string, { transaction?: RpcTx; error?: string }>

const keyAddress = (key: Key | undefined) => typeof key === 'string' ? key : key?.pubkey
const median = (values: Array<number | null>) => { const list = values.filter((value): value is number => typeof value === 'number').sort((a,b)=>a-b); if (!list.length) return null; const middle=Math.floor(list.length/2); return list.length%2 ? list[middle] : (list[middle-1]+list[middle])/2 }
const counts = (values: Array<string | null | undefined>) => { const out=new Map<string,number>(); values.forEach((value)=>{if(value)out.set(value,(out.get(value)??0)+1)}); return [...out].sort((a,b)=>b[1]-a[1]).map(([value,total])=>({value,total})) }
const share = (values: string[], limit: number) => values.length ? counts(values).slice(0,limit).reduce((sum,row)=>sum+row.total,0)/values.length : null
const hhi = (values: string[]) => values.length ? counts(values).reduce((sum,row)=>sum+(row.total/values.length)**2,0) : null

function programIds(tx: RpcTx) {
  const keys=tx.transaction?.message?.accountKeys ?? []
  const instructions=[...(tx.transaction?.message?.instructions ?? []),...(tx.meta?.innerInstructions?.flatMap((group)=>group.instructions ?? []) ?? [])]
  return [...new Set(instructions.map((instruction)=>instruction.programId ?? (typeof instruction.programIdIndex==='number' ? keyAddress(keys[instruction.programIdIndex]) : undefined)).filter((id):id is string=>Boolean(id)))]
}

function balances(tx: RpcTx) {
  const pre=new Map((tx.meta?.preTokenBalances??[]).filter((row)=>row.mint===TOAD_MINT).map((row)=>[row.accountIndex,row]))
  const post=new Map((tx.meta?.postTokenBalances??[]).filter((row)=>row.mint===TOAD_MINT).map((row)=>[row.accountIndex,row]))
  return [...new Set([...pre.keys(),...post.keys()])].map((accountIndex)=>{ const before=pre.get(accountIndex), after=post.get(accountIndex), preAmount=before?.uiTokenAmount?.amount??'0',postAmount=after?.uiTokenAmount?.amount??'0'; return {accountIndex,owner:after?.owner??before?.owner??null,decimals:after?.uiTokenAmount?.decimals??before?.uiTokenAmount?.decimals??null,preAmount,postAmount,deltaAmount:(BigInt(postAmount)-BigInt(preAmount)).toString(),evidence:'observed'} })
}

function extract(entry: Entry, tx: RpcTx) {
  const keys=tx.transaction?.message?.accountKeys??[]
  const signers=keys.filter((key):key is Exclude<Key,string>=>typeof key!=='string'&&Boolean(key.signer)).map((key)=>key.pubkey).filter((id):id is string=>Boolean(id))
  const budget=collectComputeBudget(tx), priority=derivePriorityFeeLamports(tx,budget), state=deriveExecutionState(tx)
  const rawFailure=findExplicitProgramError(tx,(id)=>`Program ${id.slice(0,4)}...${id.slice(-4)}`)
  const documentedFailure=rawFailure&&!rawFailure.name?{...rawFailure,name:'opaque-custom-error'}:rawFailure
  const noProfit=(tx.meta?.logMessages??[]).find((line)=>/\bno_profit\b|\bno profitable\b.*\b(route|pair)\b/i.test(line))??null
  return { signature:entry.signature, metadata:entry.metadata, slot:tx.slot??null, blockTime:tx.blockTime??null, execution:{state,evidence:'observed'}, signers:{addresses:signers,evidence:signers.length?'observed':'unknown'}, primarySigner:signers[0]??null,
    fees:{totalLamports:typeof tx.meta?.fee==='number'?tx.meta.fee:null,evidence:typeof tx.meta?.fee==='number'?'observed':'unknown',priorityFeeLamports:priority.amountLamports,priorityFeeEvidence:priority.derivation?'derived':'unknown',priorityFeeFormula:priority.derivation?.formula??null},
    compute:{requestedCU:budget.computeUnitLimit,consumedCU:tx.meta?.computeUnitsConsumed??null,cuPriceMicroLamports:budget.computeUnitPriceMicroLamports,evidence:'observed'}, programs:programIds(tx).map((id)=>({id,evidence:'observed'})), writableAccounts:keys.filter((key):key is Exclude<Key,string>=>typeof key!=='string'&&Boolean(key.writable)&&Boolean(key.pubkey)).map((key)=>({address:key.pubkey!,evidence:'observed'})), documentedFailure:documentedFailure?{...documentedFailure,evidence:'observed'}:null, noProfitFailure:noProfit&&state==='landed-but-failed'?{log:noProfit,evidence:'observed'}:null, toadTokenBalances:balances(tx) }
}

async function fetchAll(entries: Entry[], cache: Cache, apiKey: string, cachePath: string) {
  const missing=entries.map((entry)=>entry.signature).filter((signature)=>!cache[signature])
  for(let offset=0;offset<missing.length;offset+=10) {
    const batch=missing.slice(offset,offset+10); let body: Array<{id?:number;result?:RpcTx|null;error?:{message?:string}}> | null=null
    for(let attempt=0;attempt<6;attempt+=1) { const response=await fetch(`https://mainnet.helius-rpc.com/?api-key=${apiKey}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(batch.map((signature,id)=>({jsonrpc:'2.0',id,method:'getTransaction',params:[signature,{encoding:'jsonParsed',maxSupportedTransactionVersion:0}]})))}); const text=await response.text(); if(response.ok){try{body=JSON.parse(text)}catch{body=null}} if(Array.isArray(body))break; if(attempt===5)throw new Error(`RPC batch failed (${response.status}): ${text.slice(0,120)}`); await new Promise((resolve)=>setTimeout(resolve,5000*(attempt+1))) }
    for(const item of body??[]) { const signature=typeof item.id==='number'?batch[item.id]:undefined; if(signature)cache[signature]=item.result?{transaction:item.result}:{error:item.error?.message??'Transaction not returned'} }
    if((offset/10+1)%20===0||offset+10>=missing.length)await writeFile(cachePath,JSON.stringify(cache))
    console.log(`Fetched ${Math.min(offset+10,missing.length)}/${missing.length} missing receipts.`)
    if(offset+10<missing.length)await new Promise((resolve)=>setTimeout(resolve,1500))
  }
}

function analyze(records: ReturnType<typeof extract>[], sampling: unknown) {
  const ordered=records.filter((record)=>typeof record.slot==='number').sort((a,b)=>a.slot!-b.slot!), start=ordered[0]?.slot??0,end=ordered.at(-1)?.slot??0,width=Math.max(1,Math.ceil((end-start+1)/SLICE_COUNT))
  const bins=Array.from({length:SLICE_COUNT},(_,index)=>({index:index+1,start:start+index*width,end:Math.min(end,start+(index+1)*width-1),items:[] as typeof ordered})); ordered.forEach((record)=>bins[Math.min(SLICE_COUNT-1,Math.floor((record.slot!-start)/width))].items.push(record))
  const seen=new Set<string>(), first=new Map<string,number>(); const slices=bins.map((bin)=>{const items=bin.items,success=items.filter((x)=>x.execution.state==='landed'),failure=items.filter((x)=>x.execution.state==='landed-but-failed'),signers=[...new Set(items.map((x)=>x.primarySigner).filter((x):x is string=>Boolean(x)))],newSigners=signers.filter((s)=>!first.has(s)),returning=signers.filter((s)=>seen.has(s));newSigners.forEach((s)=>first.set(s,bin.index));signers.forEach((s)=>seen.add(s));const signerValues=items.map((x)=>x.primarySigner).filter((x):x is string=>Boolean(x));return {slice:bin.index,slotStart:bin.start,slotEnd:bin.end,transactions:items.length,successes:success.length,failures:failure.length,successRate:items.length?success.length/items.length:null,failureRate:items.length?failure.length/items.length:null,noProfit:failure.filter((x)=>x.noProfitFailure).length,opaque:failure.filter((x)=>!x.noProfitFailure&&(!x.documentedFailure||x.documentedFailure.name==='opaque-custom-error')).length,otherDocumented:failure.filter((x)=>!x.noProfitFailure&&x.documentedFailure&&x.documentedFailure.name!=='opaque-custom-error').length,medianFee:median(items.map((x)=>x.fees.totalLamports)),medianPriorityFee:median(items.map((x)=>x.fees.priorityFeeLamports)),medianRequestedCU:median(items.map((x)=>x.compute.requestedCU)),medianConsumedCU:median(items.map((x)=>x.compute.consumedCU)),uniqueSigners:signers.length,newSigners:newSigners.length,returningSigners:returning.length,successfulNewSigners:newSigners.filter((s)=>success.some((x)=>x.primarySigner===s)).length,successfulReturningSigners:returning.filter((s)=>success.some((x)=>x.primarySigner===s)).length,returningFailingSigners:returning.filter((s)=>failure.some((x)=>x.primarySigner===s)).length,top1Share:share(signerValues,1),top5Share:share(signerValues,5),top10Share:share(signerValues,10),hhi:hhi(signerValues)}})
  const groups=new Map<string,typeof ordered>();ordered.forEach((record)=>{if(record.primarySigner)groups.set(record.primarySigner,[...(groups.get(record.primarySigner)??[]),record])});const sequence={successSuccess:0,successFailureSuccess:0,failureSuccess:0,failureFailure:0},firstSuccess: Array<{appearsAgain:boolean;successAgain:boolean}>=[],firstFailure: Array<{appearsAgain:boolean;successAgain:boolean}>=[]
  for(const items of groups.values()){const states=items.map((item)=>item.execution.state),later=states.slice(1),firstState=states[0];if(firstState==='landed')firstSuccess.push({appearsAgain:later.length>0,successAgain:later.includes('landed')});if(firstState==='landed-but-failed')firstFailure.push({appearsAgain:later.length>0,successAgain:later.includes('landed')});for(let index=1;index<states.length;index+=1){if(states[index-1]==='landed'&&states[index]==='landed')sequence.successSuccess++;if(states[index-1]==='landed-but-failed'&&states[index]==='landed')sequence.failureSuccess++;if(states[index-1]==='landed-but-failed'&&states[index]==='landed-but-failed')sequence.failureFailure++;if(index>=2&&states[index-2]==='landed'&&states[index-1]==='landed-but-failed'&&states[index]==='landed')sequence.successFailureSuccess++}}
  const rate=(items:Array<{appearsAgain:boolean;successAgain:boolean}>,field:'appearsAgain'|'successAgain')=>items.length?items.filter((item)=>item[field]).length/items.length:null;const success=ordered.filter((x)=>x.execution.state==='landed'),failure=ordered.filter((x)=>x.execution.state==='landed-but-failed'),noProfit=failure.filter((x)=>x.noProfitFailure),allSigners=ordered.map((x)=>x.primarySigner).filter((x):x is string=>Boolean(x)),successSigners=success.map((x)=>x.primarySigner).filter((x):x is string=>Boolean(x))
  return {coverage:{startSlot:start,endSlot:end,sampling},totals:{transactions:ordered.length,successes:success.length,failures:failure.length,uniquePrimarySigners:groups.size},slices,recurrence:{firstSuccess:firstSuccess.length,firstSuccessAppearsAgain:rate(firstSuccess,'appearsAgain'),firstSuccessSucceedsAgain:rate(firstSuccess,'successAgain'),firstFailure:firstFailure.length,firstFailureAppearsAgain:rate(firstFailure,'appearsAgain'),firstFailureSucceedsAgain:rate(firstFailure,'successAgain'),sequence},concentration:{top1Share:share(allSigners,1),top5Share:share(allSigners,5),top10Share:share(allSigners,10),hhi:hhi(allSigners),successTop1Share:share(successSigners,1),successTop5Share:share(successSigners,5)},failureClasses:counts(failure.map((x)=>x.noProfitFailure?'explicit-no-profit-or-route':x.documentedFailure?.name??'undocumented')),noProfit:{count:noProfit.length,uniquePrimarySigners:new Set(noProfit.map((x)=>x.primarySigner).filter(Boolean)).size,topSigners:counts(noProfit.map((x)=>x.primarySigner)).slice(0,10),programs:counts(noProfit.map((x)=>x.documentedFailure?.programId))},programEcology:{successful:counts(success.flatMap((x)=>x.programs.map((p)=>p.id))).slice(0,20),failed:counts(failure.flatMap((x)=>x.programs.map((p)=>p.id))).slice(0,20)}}
}

async function main(){const inputPath=path.resolve(process.argv[2]??'research/toad-large-signatures-merged.json'),outputDir=path.resolve(process.argv[3]??'research'),cachePath=path.join(outputDir,'toad-large-rpc-cache.json'),input=JSON.parse(await readFile(inputPath,'utf8')) as {sampling?:unknown;transactions?:Entry[]},env=await readFile('.env.local','utf8'),apiKey=env.match(/^HELIUS_API_KEY=(.+)$/m)?.[1]?.trim();if(!apiKey)throw new Error('HELIUS_API_KEY is required.');await mkdir(outputDir,{recursive:true});let cache:Cache={};try{cache=JSON.parse(await readFile(cachePath,'utf8'))}catch{}const entries=input.transactions??[];await fetchAll(entries,cache,apiKey,cachePath);const output=entries.map((entry)=>cache[entry.signature]?.transaction?extract(entry,cache[entry.signature].transaction!):{signature:entry.signature,metadata:entry.metadata,fetchError:cache[entry.signature]?.error??'Missing cache entry'}),complete=output.filter((entry):entry is ReturnType<typeof extract>=>'execution'in entry),study=analyze(complete,input.sampling);await writeFile(path.join(outputDir,'toad-large-study.json'),JSON.stringify({generatedAt:new Date().toISOString(),evidenceBoundary:'Observed transaction data, deterministic derived aggregates, and non-causal patterns.',fetchFailures:output.filter((entry)=>'fetchError'in entry),records:output,study},null,2));await writeFile(path.join(outputDir,'toad-large-study.md'),`# TOAD Large Execution Study\n\nThis is a systematically selected partial transaction study, not a complete record of all TOAD activity or token holders.\n\n\`toad-large-study.json\` contains all observed records and derived aggregates.\n\n## Study Summary\n\n${JSON.stringify(study,null,2)}\n`);console.log(`Wrote study for ${complete.length} receipts; ${output.length-complete.length} fetch failures.`)}
void main()
