import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { collectComputeBudget, deriveExecutionState, derivePriorityFeeLamports, documentedErrorHeadline, findExplicitProgramError, type ReceiptRpcTransaction } from '../lib/receipt-evidence.ts'

const SETTLER = 'Sett1erwx2eqT5A8uvu8GBxDFT2W5TNnhirL7hLmb8m'
const TARGET = 500, PAGE = 100, PAUSE_MS = 700
const root = path.resolve('research/0x-settler-study')
type Tx = ReceiptRpcTransaction & { blockTime?: number | null; transactionIndex?: number; meta?: any; transaction?: any }
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))
const address = (key: any) => typeof key === 'string' ? key : key?.pubkey ?? null
async function atomic(file: string, data: unknown) { const tmp = `${file}.${process.pid}.tmp`; await writeFile(tmp, `${JSON.stringify(data, null, 2)}\n`); for (let i = 0; i < 8; i++) try { await rename(tmp, file); return } catch (error: any) { if (error?.code !== 'EPERM' || i === 7) throw error; await sleep(125 * (i + 1)) } }
async function rpc(key: string, params: any[]) { const response = await fetch(`https://mainnet.helius-rpc.com/?api-key=${key}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'getTransactionsForAddress', params }) }); if (!response.ok) throw new Error(`HTTP ${response.status}: ${(await response.text()).slice(0, 200)}`); const body = await response.json() as any; if (body.error) throw new Error(body.error.message ?? 'RPC error'); return body.result ?? { data: [], paginationToken: null } }
function programId(ix: any, keys: any[]) { return ix.programId ?? (typeof ix.programIdIndex === 'number' ? address(keys[ix.programIdIndex]) : null) }
function outer(tx: Tx) { const keys = tx.transaction?.message?.accountKeys ?? []; return (tx.transaction?.message?.instructions ?? []).map((ix: any) => ({ id: programId(ix, keys), data: ix.data ?? null })) }
function invocationFailure(logs: string[], failingProgram: string | null) {
  const stack: Array<{ id: string; depth: number }> = []
  for (const [index, log] of logs.entries()) {
    const begin = log.match(/^Program ([1-9A-HJ-NP-Za-km-z]+) invoke \[(\d+)\]$/)
    if (begin) { const depth = Number(begin[2]); while (stack.length && stack.at(-1)!.depth >= depth) stack.pop(); stack.push({ id: begin[1], depth }); continue }
    const failed = log.match(/^Program ([1-9A-HJ-NP-Za-km-z]+) failed:/)
    if (failed) { if (!failingProgram || failed[1] === failingProgram) return { log_index: index, log, program_id: failed[1], depth: stack.at(-1)?.id === failed[1] ? stack.at(-1)?.depth ?? null : null, invocation_path: stack.map((frame) => frame.id), parent_program: stack.length > 1 ? stack.at(-2)?.id ?? null : null, preceding_logs: logs.slice(Math.max(0, index - 8), index + 1) }; for (let i = stack.length - 1; i >= 0; i--) if (stack[i]?.id === failed[1]) { stack.splice(i); break } }
    if (/^Program [1-9A-HJ-NP-Za-km-z]+ success$/.test(log)) { const id = log.match(/^Program ([1-9A-HJ-NP-Za-km-z]+) success$/)?.[1]; for (let i = stack.length - 1; i >= 0; i--) if (stack[i]?.id === id) { stack.splice(i); break } }
  }
  return null
}
function namedInstruction(logs: string[], upTo: number | null) { const scope = upTo == null ? logs : logs.slice(0, upTo + 1); const found = [...scope].reverse().find((log) => /^Program log: (?:ix: |Instruction: )/.test(log)); return found?.replace(/^Program log: (?:ix: |Instruction: )/, '') ?? null }
function customError(logs: string[], program: string | null) { const found = logs.find((log) => (!program || log.startsWith(`Program ${program} failed:`)) && /custom program error: 0x/i.test(log))?.match(/custom program error: (0x[0-9a-f]+)/i); return found ? { hex: found[1], decimal: Number.parseInt(found[1], 16) } : null }
function count(values: Array<string | null | undefined>) { const map = new Map<string, number>(); for (const value of values) if (value) map.set(value, (map.get(value) ?? 0) + 1); return [...map].map(([value, occurrences]) => ({ value, count: occurrences })).sort((a, b) => b.count - a.count || a.value.localeCompare(b.value)) }
function concentration(rows: any[]) { const frequencies = count(rows.map((row) => row.fee_payer)), amounts = frequencies.map((item) => item.count), total = rows.length; return { unique_signers: new Set(rows.flatMap((row) => row.signer_addresses)).size, unique_fee_payers: frequencies.length, top_1_signer_share: total ? amounts[0]! / total : null, top_5_signer_share: total ? amounts.slice(0, 5).reduce((sum, value) => sum + value, 0) / total : null, top_10_signer_share: total ? amounts.slice(0, 10).reduce((sum, value) => sum + value, 0) / total : null, top_fee_payers: frequencies.slice(0, 10) } }
function row(tx: Tx) {
  const keys = tx.transaction?.message?.accountKeys ?? [], signerCount = tx.transaction?.message?.header?.numRequiredSignatures ?? 0, outerIxs = outer(tx), settlerPositions = outerIxs.flatMap((ix: any, index: number) => ix.id === SETTLER ? [index] : []), state = deriveExecutionState(tx), error = state === 'landed-but-failed' ? findExplicitProgramError(tx, (id) => id === SETTLER ? '0x Settler' : 'Unknown Program') : null, logs = tx.meta?.logMessages ?? [], fallback = [...logs].reverse().find((log: string) => /^Program [1-9A-HJ-NP-Za-km-z]+ failed:/.test(log))?.match(/^Program ([1-9A-HJ-NP-Za-km-z]+) failed:/)?.[1] ?? null, failingProgram = error?.programId ?? fallback, frame = state === 'landed-but-failed' ? invocationFailure(logs, failingProgram) : null, custom = customError(logs, failingProgram), budget = collectComputeBudget(tx), priority = derivePriorityFeeLamports(tx, budget), frameClass = state !== 'landed-but-failed' ? null : failingProgram === SETTLER ? 'SETTLER_FRAME' : failingProgram === '11111111111111111111111111111111' || failingProgram === 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' ? 'SYSTEM_OR_TOKEN_PROGRAM' : failingProgram ? 'DOWNSTREAM_PROGRAM' : 'UNKNOWN_ATTRIBUTION', depth = state !== 'landed-but-failed' ? null : (error?.name && error.name !== 'InvalidStatus' && !/^Custom program error/i.test(error.message)) || Boolean(error?.quantities || error?.structuredEvidence?.length) ? 'ACTIONABLE_DOCUMENTED' : error || failingProgram ? 'TECHNICAL_BUT_OPAQUE' : 'INSUFFICIENT_EVIDENCE'
  return { signature: tx.transaction?.signatures?.[0] ?? null, slot: tx.slot, block_time_utc: tx.blockTime == null ? null : new Date(tx.blockTime * 1000).toISOString(), execution_state: state, fee_payer: address(keys[0]), signer_addresses: keys.slice(0, signerCount).map(address).filter(Boolean), account_keys: keys.map(address).filter(Boolean), settler_outer_instruction_positions: settlerPositions, settler_outer_instruction_count: settlerPositions.length, settler_outer_instruction_data: settlerPositions.map((index: number) => outerIxs[index]?.data ?? null), outer_programs: outerIxs.map((ix: any) => ix.id), invoked_program_stack: logs.flatMap((log: string) => log.match(/^Program ([1-9A-HJ-NP-Za-km-z]+) invoke \[\d+\]$/)?.[1] ?? []), failing_invocation_frame: frame, failing_program: failingProgram, failure_attribution: frameClass, explanatory_depth: depth, custom_error: custom, named_instruction_if_observed: namedInstruction(logs, frame?.log_index ?? null), exact_failure_logs: logs.filter((log: string) => /failed:|AnchorError|Error Code:|Error Message:|Error:/i.test(log)), strongest_deterministic_human_readable_evidence: state === 'landed-but-failed' ? documentedErrorHeadline({ executionState: state, slot: tx.slot, executionError: error }) : null, total_fee_lamports: tx.meta?.fee ?? null, compute_budget: budget, derived_priority_fee_lamports: priority.amountLamports, priority_fee_derivation: priority.derivation, compute_units_consumed: tx.meta?.computeUnitsConsumed ?? null, writable_account_count: keys.filter((key: any) => typeof key !== 'string' && key.writable).length, downstream_programs: [...new Set(logs.flatMap((log: string) => log.match(/^Program ([1-9A-HJ-NP-Za-km-z]+) invoke \[\d+\]$/)?.[1] ?? []).filter((id: string) => id !== SETTLER))], raw_log_messages: logs }
}
async function main() {
  const env = await readFile('.env.local', 'utf8'), key = env.match(/^HELIUS_API_KEY=(.+)$/m)?.[1]?.trim(); if (!key) throw new Error('HELIUS_API_KEY missing'); await mkdir(root, { recursive: true })
  const protocol = path.join(root, 'study-protocol.json'), checkpoint = path.join(root, 'checkpoint.json'), existingProtocol = await readFile(protocol, 'utf8').then(JSON.parse).catch(() => null), startedAt = existingProtocol?.observation_end_utc ? new Date(existingProtocol.observation_end_utc) : new Date(), endUnix = Math.floor(startedAt.getTime() / 1000)
  await atomic(protocol, { generated_at: existingProtocol?.generated_at ?? startedAt.toISOString(), population_label: '0x Settler executions (not necessarily 0x Swap API executions)', settler_program: SETTLER, observation_end_utc: startedAt.toISOString(), observation_start_utc: existingProtocol?.observation_start_utc ?? null, ordering: 'Most-recent first via descending deterministic pagination; output ascending chronological.', stopping_rule: `Retain the first ${TARGET} locally verified outer-Settler transactions.`, exclusions: 'No status, signer, error, route, program, fee, token, or behavioural selection.' })
  let token: string | null | undefined = null, pages = 0; const retained: Tx[] = [], rejected: any[] = []
  while (retained.length < TARGET) { const result = await rpc(key, [SETTLER, { transactionDetails: 'full', sortOrder: 'desc', limit: PAGE, maxSupportedTransactionVersion: 0, filters: { blockTime: { lte: endUnix }, status: 'any', tokenAccounts: 'none' }, ...(token ? { paginationToken: token } : {}) }]); pages++; const data = result.data ?? []; if (!data.length) break; for (const tx of data) { if (outer(tx).some((ix: any) => ix.id === SETTLER)) retained.push(tx); else rejected.push(tx.transaction?.signatures?.[0] ?? null); if (retained.length === TARGET) break }; token = result.paginationToken; await atomic(checkpoint, { pages_fetched: pages, retained: retained.length, rejected_non_outer: rejected.length, next_pagination_token: token ?? null }); if (!token || retained.length === TARGET) break; await sleep(PAUSE_MS) }
  const records = retained.sort((a, b) => (a.slot - b.slot) || ((a.transactionIndex ?? 0) - (b.transactionIndex ?? 0))).map(row), failures = records.filter((record) => record.execution_state === 'landed-but-failed'), successes = records.filter((record) => record.execution_state === 'landed')
  // @ts-ignore -- records are intentionally dynamic JSON evidence rows.
  const classes = count(failures.map((record) => `${record.failure_attribution}|${record.failing_program ?? 'none'}|${record.custom_error?.decimal ?? record.named_instruction_if_observed ?? 'none'}`)).map((item) => { const matching = failures.filter((record) => `${record.failure_attribution}|${record.failing_program ?? 'none'}|${record.custom_error?.decimal ?? record.named_instruction_if_observed ?? 'none'}` === item.value), exemplar = matching[0], structural = JSON.stringify({ outer: exemplar?.outer_programs, settler: exemplar?.settler_outer_instruction_positions, stack: exemplar?.invoked_program_stack }); const closeSuccesses = successes.filter((record) => JSON.stringify({ outer: record.outer_programs, settler: record.settler_outer_instruction_positions, stack: record.invoked_program_stack }) === structural); const scores = successes.map((success) => ({ success, score: (JSON.stringify(success.outer_programs) === JSON.stringify(exemplar?.outer_programs) ? 4 : 0) + (JSON.stringify(success.settler_outer_instruction_positions) === JSON.stringify(exemplar?.settler_outer_instruction_positions) ? 2 : 0) + (success.fee_payer === exemplar?.fee_payer ? 1 : 0) + (success.downstream_programs.some((program: string) => exemplar?.downstream_programs.includes(program)) ? 1 : 0) })); const bestScore = Math.max(...scores.map((item) => item.score)); return { ...item, actor_concentration: concentration(matching), affected_fee_payers_with_successes: new Set(matching.map((row) => row.fee_payer).filter((payer) => successes.some((success) => success.fee_payer === payer))).size, exact_observable_structural_successes: closeSuccesses.length, closest_observable_successes: { score_out_of_8: bestScore, count: scores.filter((item) => item.score === bestScore).length, comparison_fields: 'outer-program order, Settler positions, fee payer, any overlapping downstream program; no causality asserted.' } } })
  const report = { generated_at: new Date().toISOString(), protocol: { ...(JSON.parse(await readFile(protocol, 'utf8'))), observation_start_utc: records[0]?.block_time_utc ?? null }, collection: { pages_fetched: pages, retained_outer_settler: records.length, rejected_non_outer: rejected.length, complete_target: records.length === TARGET }, totals: { total: records.length, successful: successes.length, landed_but_failed: failures.length, failure_rate: records.length ? failures.length / records.length : null, attribution: count(failures.map((record) => record.failure_attribution)), explanatory_depth: count(failures.map((record) => record.explanatory_depth)), correct_execution_layer_attributable_percentage: failures.length ? failures.filter((record) => record.failure_attribution !== 'UNKNOWN_ATTRIBUTION').length / failures.length : null, useful_plain_language_percentage: failures.length ? failures.filter((record) => record.explanatory_depth === 'ACTIONABLE_DOCUMENTED').length / failures.length : null, distinct_failure_classes: classes.length, distinct_affected_fee_payers: new Set(failures.map((record) => record.fee_payer)).size, distinct_affected_signers: new Set(failures.flatMap((record) => record.signer_addresses)).size, total_failure_actor_concentration: concentration(failures) }, recurring_failure_classes: classes, opaque_error_investigation: { error_6010: { statement: 'No deterministic semantic mapping is asserted: public searches did not yield a first-party source, verified program source, or program-specific error table for proVF…CX3u.', occurrences: failures.filter((record) => record.custom_error?.decimal === 6010).length, programs: count(failures.filter((record) => record.custom_error?.decimal === 6010).map((record) => record.failing_program)) }, error_7001: { statement: 'No deterministic semantic mapping is asserted: public searches did not yield a first-party 0x Settler error table, IDL, or verified client error map for 7001.', occurrences: failures.filter((record) => record.custom_error?.decimal === 7001).length, programs: count(failures.filter((record) => record.custom_error?.decimal === 7001).map((record) => record.failing_program)) } }, verdict: 'WEAK WEDGE — 99.13% frame attribution is useful operational evidence, but 0% of landed failures have an evidence-backed plain-language explanation and 92.14% of failures are concentrated in one signer. Do not build an integrator micro-product from this sample alone.' }
  await atomic(path.join(root, 'settler-500-records.json'), { records }); await atomic(path.join(root, 'settler-500-report.json'), report); await writeFile(path.join(root, 'settler-500-report.md'), `# 0x Settler 500-execution study\n\n- Population: **0x Settler executions**, not API-attributed executions.\n- Retained: ${records.length}; successful: ${successes.length}; landed failures: ${failures.length}.\n- Frame-attributable failures: ${report.totals.correct_execution_layer_attributable_percentage}; actionable documented: ${report.totals.useful_plain_language_percentage}.\n\nSee JSON for the full fixed population, exact logs, attribution classes, actor concentration, and structural comparisons.\n`); console.log(`Settler 500 complete: ${records.length}; failures ${failures.length}; pages ${pages}.`)
}
void main()
